config/routes.rb
Rails.application.routes.draw do
  root to: "site#root"
  get 'landing',  to: "site#landing", as: :landing
  
  get "/auth/:provider/callback" => "sessions#oauth"
  
  resource :session, only: [:create, :new, :destroy]
  resources :users
  
  namespace :api, defaults: { format: :json } do
    resources :lists, only: [:create, :show, :index, :destroy, :update]
    
    resources :tasks, only: [:create, :show, :index, :destroy, :update]
    
    resources :list_shares, only: [:create, :destroy]
    
    resources :notifications, only: [:index, :update]
    
    resources :users, only: [:index]
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :require_signed_in, only: [:root]
  before_action :require_signed_out, only: [:landing]
  
  def root
  end
  
  def landing
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/site/landing.html.erb
<div class="landing-page background-image">
  
  <section id="landing-modal" class="Absolute-Center group">
    
    <div class="Center-Container">
    
      <img class="logo-with-text" src="<%= asset_url('logo_with_text.png') %>">

      <div class="landing-buttons">
        <div class="oauth-buttons">
          <%= link_to "Facebook", "/auth/facebook", id:"facebook-button" %>
          <%= link_to "Google", "/auth/google_oauth2", id:"google-button"%>
        </div>
        
        <%= link_to "Demo Account", users_path, method: :post, class: "try-it-button" %>
        <a class="create-account-button" href="<%= new_user_url %>">
          Create Free Account
        </a>
        <a class="sign-in-button" href="<%= new_session_url %>">
          Sign In
        </a>
      
      </div>
        
    </div>
      
  </section>
  
</div>

app/views/site/root.html.erb
<div class="app-container group">
  
  <section class="sidebar">  
    <%= render partial: "users/nav" %>
    
    <nav id="lists-index"></nav>
  </section>

  <div id="content-container" class="group">
    <section id="content">
    </section>
    <section id="side-content"></section>
  </div>
  
  <div id="modal-container">
  </div>
  
</div>

<script src="//js.pusher.com/2.2/pusher.min.js" type="text/javascript"></script>
<script>

$(document).ready(function(){
  if(<%= signed_in? %>){
   Wunderclone.currentUserId = <%= current_user.id %>; 
    Wunderclone.otherUsers = {};
    $.getJSON("api/users", function(data){
      data.forEach(function(user_data){
        Wunderclone.otherUsers[user_data['email']] = user_data['id'];
      })
    });
  
    var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>');
    var channel = pusher.subscribe('notifications-' + <%= current_user.id %>);
    channel.bind('new', function(data){
      var list = new Wunderclone.Models.List(data.list_data.json);
      Wunderclone.Collections.lists.add(list);
      Wunderclone.Collections.notifications.fetch();
    })
  
    channel.bind('update', function(data){
      var list_data = data.list_data.json;
      var list_id = data.list_id;
      var list = Wunderclone.Collections.lists.get(list_id);
    })
  
    channel.bind('destroy', function(data){
      Wunderclone.Collections.lists.remove(data.list_id);
    })
    
    channel.bind('new-shared-task', function(data){
      var task_data = data.task_data.json
      var task = new Wunderclone.Models.Task(task_data);
      var list_id = task.get("list_id");
      var list = Wunderclone.Collections.lists.get(list_id);
      list.activeTasks().add(task);
    })
    
    channel.bind('delete-shared-task', function(data){
      var task_data = data.task_data.json;
      var task = Wunderclone.Collections.tasks.get(task_data.id);
      if (task){
        var list_id = task.get("list_id");
        var list = Wunderclone.Collections.lists.get(list_id);
        list.activeTasks().remove(task);
        list.completedTasks().remove(task);
      }
    })
    
    channel.bind('update-shared-task', function(data, task_id){
      var task_data = data.task_data.json;
      var task = Wunderclone.Collections.tasks.get(data.task_id);
      if (task.attributes != task_data){
        task.set(task_data); 
      }
    })
      
  }
});


</script>